### ISSUE TITLE
Proxy related error

### ISSUE THREAD

**Issue by o0Rh0mbus0o** [obskyr/thehylia#7]
I experienced this error when executing:
`python thehylia.py sen-to-chihiro-no-kamikakushi-spirited-away`

`Traceback (most recent call last):
  File "thehylia.py", line 513, in <module>
    doIt()
  File "thehylia.py", line 511, in doIt
    raise e
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='*****.*****.*****.com', port=****): Read timed out. (read timeout=10)`

I have censored the url of my proxy.

**Comment by obskyr** [comment]
Hmm. Does this always happen with every soundtrack, or is it just sometimes or with certain soundtracks? Does downloading the files through the proxy via your browser work?

**Comment by febridev** [comment]
i got same error in soundtrack bleach-original-soundtrack-i
