### ISSUE TITLE
"TypeError: 'NoneType' object is not callable" occurs when trying any album

### ISSUE THREAD

**Issue by svioletg** [obskyr/thehylia#8]
Hi! I've tried to get multiple different albums, but unfortunately each one gives me the same error:

```
$ python3 thehylia.py 11930
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/thehylia/issues.
Attach the following error message:

Traceback (most recent call last):
  File "thehylia.py", line 498, in <module>
    doIt()
  File "thehylia.py", line 474, in doIt
    download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "thehylia.py", line 363, in download
    Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "thehylia.py", line 287, in download
    for song in self.songs:
  File "thehylia.py", line 125, in lazyVersion
    setattr(self, attrName, func(self))
  File "thehylia.py", line 250, in songs
    anchors = table('a')
TypeError: 'NoneType' object is not callable
```

Any help is appreciated, and I can provide any more info if need be.

EDIT: I've also tried using the name instead of the number, however that then causes the following error instead:

```
$ python3 thehylia.py fullmetal-alchemist-brotherhood-original-soundtrack-1
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/thehylia/issues.
Attach the following error message:

Traceback (most recent call last):
  File "thehylia.py", line 498, in <module>
    doIt()
  File "thehylia.py", line 474, in doIt
    download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "thehylia.py", line 363, in download
    Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "thehylia.py", line 288, in download
    files.append(getAppropriateFile(song, formatOrder))
  File "thehylia.py", line 158, in getAppropriateFile
    return song.files[0]
IndexError: list index out of range
```

**Comment by obskyr** [comment]
Hmm, I can't reproduce the issue. First of all, make sure you have the very latest version of `theylia.py`. If it doesn't work when you do: if you run the following commands, what is the output?

```bash
python3 -V
pip3 show requests
pip3 show beautifulsoup4
```

**Comment by svioletg** [comment]
This is the output I recieved:
```
$ python3 -V
Python 3.4.3
```
```
$ pip3 show requests
---
Name: requests
Version: 2.2.1
Location: /usr/lib/python3/dist-packages
Requires:
```
```
$ pip3 show beautifulsoup4
---
Name: beautifulsoup4
Version: 4.2.1
Location: /usr/lib/python3/dist-packages
Requires:
```
